version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: kakaroto
    ports:
      - "3306:3306"
    volumes:
      - kakaroto_data:/var/lib/mysql

volumes:
  kakaroto_data: