version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: mysql-container-jdbc
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: anime_store
    ports:
      - "3308:3306"
    volumes:
      - container_test_data:/var/lib/mysql

volumes:
  container_test_data: